import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className="relative h-screen ">
          <div
            className="absolute inset-0 bg-cover bg-center blur-sm"
            style={{ backgroundImage: "url('/elden.jpg')", zIndex: -1 }}
          >
            <div className="w-100 bottom-0 h-full bg-gradient-to-t from-black to-transparent" />

          </div>
          <div className="relative z-10">
            <NavBar />
            {children}
          </div>
        </div>


      </body>
    </html>
  );
}
